import type { Theme } from "../types";

/** 提供接近 VSCodium Visual Studio Dark 的中性深色主题。 */
export const codiumDark: Theme = {
  id: "codium-dark",
  name: "Codium Dark",
  description: "Neutral dark palette based on VSCodium Visual Studio Dark.",
  editorTheme: { dark: "codium-dark", light: "codium-light" },
  variants: {
    dark: {
      colors: {
        background: "#1e1e1e",
        foreground: "#d4d4d4",
        card: "#252526",
        cardForeground: "#d4d4d4",
        popover: "#252526",
        popoverForeground: "#d4d4d4",
        primary: "#007acc",
        primaryForeground: "#ffffff",
        secondary: "#2d2d30",
        secondaryForeground: "#d4d4d4",
        muted: "#2d2d30",
        mutedForeground: "#9d9d9d",
        accent: "#37373d",
        accentForeground: "#ffffff",
        destructive: "#f44747",
        border: "#3e3e42",
        input: "#3e3e42",
        ring: "#007acc",
        sidebar: "#252526",
        sidebarForeground: "#cccccc",
        sidebarPrimary: "#007acc",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#2a2d2e",
        sidebarAccentForeground: "#ffffff",
        sidebarBorder: "#3e3e42",
        sidebarRing: "#007acc",
      },
      terminal: {
        cursor: "#aeafad",
        cursorAccent: "#1e1e1e",
        selection: "rgba(38,79,120,0.65)",
        ansi: [
          "#1e1e1e",
          "#cd3131",
          "#0dbc79",
          "#e5e510",
          "#2472c8",
          "#bc3fbc",
          "#11a8cd",
          "#e5e5e5",
          "#666666",
          "#cd3131",
          "#14ce14",
          "#e5e510",
          "#5c9bd1",
          "#bc3fbc",
          "#11a8cd",
          "#e5e5e5",
        ],
      },
    },
    light: {
      colors: {
        background: "#ffffff",
        foreground: "#1e1e1e",
        card: "#f3f3f3",
        cardForeground: "#1e1e1e",
        popover: "#ffffff",
        popoverForeground: "#1e1e1e",
        primary: "#006ab1",
        primaryForeground: "#ffffff",
        secondary: "#e8e8e8",
        secondaryForeground: "#1e1e1e",
        muted: "#e8e8e8",
        mutedForeground: "#616161",
        accent: "#e4e6f1",
        accentForeground: "#1e1e1e",
        destructive: "#cd3131",
        border: "#d4d4d4",
        input: "#cecece",
        ring: "#006ab1",
        sidebar: "#f3f3f3",
        sidebarForeground: "#333333",
        sidebarPrimary: "#006ab1",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#e8e8e8",
        sidebarAccentForeground: "#1e1e1e",
        sidebarBorder: "#d4d4d4",
        sidebarRing: "#006ab1",
      },
      terminal: {
        cursor: "#000000",
        cursorAccent: "#ffffff",
        selection: "rgba(173,214,255,0.75)",
        ansi: [
          "#000000",
          "#cd3131",
          "#008000",
          "#795e26",
          "#0451a5",
          "#bc05bc",
          "#0598bc",
          "#5a5a5a",
          "#666666",
          "#cd3131",
          "#14ce14",
          "#b5ba00",
          "#0451a5",
          "#bc05bc",
          "#0598bc",
          "#a5a5a5",
        ],
      },
    },
  },
};
