import { useMemo } from "react";
import { useSessionStore } from "@renderer/stores/sessionStore.js";
import { cn } from "@renderer/lib/cn.js";
import { useI18n } from "@renderer/lib/i18n/index.js";
import { Select, Switch } from "@renderer/components/ui/index.js";
import { IconRobot } from "@renderer/lib/icons.js";
import { SettingRow } from "./SettingRow.js";
import { SettingsSection } from "./SettingsSection.js";

/**
 * Thread-title generation settings.
 *
 * Two controls:
 *  - **Auto generate** (toggle): when on, the main process fires a one-shot
 *    LLM call on a session's first user message to produce a short Chinese
 *    title, overwriting the default placeholder. When off, the placeholder
 *    (first 40 chars of the prompt) is kept.
 *  - **Generation model**: pick a SPECIFIC model (supplier + model id).
 *    Only custom-model configs with at least one model are listed; the
 *    user must have configured models first. There is no default model —
 *    until one is picked, titles are not generated.
 *
 * The model value is stored as `"configId:modelId"` in the settings table,
 * same shape as the commit-gen / conflict-resolve model selectors.
 *
 * Renders as its own SettingsSection (card) so it slots into GeneralPanel as
 * a sibling section.
 */
export function TitleGenPanel() {
  const { t } = useI18n();
  const titleGenEnabled = useSessionStore((s) => s.titleGenEnabled);
  const titleGenModel = useSessionStore((s) => s.titleGenModel);
  const setTitleGenEnabled = useSessionStore((s) => s.setTitleGenEnabled);
  const setTitleGenModel = useSessionStore((s) => s.setTitleGenModel);
  const customModels = useSessionStore((s) => s.customModels);

  // Build a flat list of selectable models: one entry per (config, model).
  // Each entry's value is `"configId:modelId"`, label is `"供应商名 -> 模型id"`.
  const modelOptions = useMemo(() => {
    const opts: { value: string; label: string }[] = [];
    for (const cfg of customModels) {
      for (const entry of cfg.models) {
        if (entry.id.trim()) {
          opts.push({
            value: `${cfg.id}:${entry.id}`,
            label: `${cfg.name} -> ${entry.id}`,
          });
        }
      }
    }
    return opts;
  }, [customModels]);

  return (
    <SettingsSection
      title={t("settings.titleGen.sectionTitle")}
      desc={t("settings.titleGen.sectionDesc")}
    >
      {/* Auto-generate toggle */}
      <SettingRow
        title={t("settings.titleGen.autoGenerate")}
        desc={t("settings.titleGen.autoGenerateDesc")}
        htmlFor="setting-titlegen-enabled"
      >
        <Switch
          id="setting-titlegen-enabled"
          checked={titleGenEnabled}
          onCheckedChange={setTitleGenEnabled}
          label={titleGenEnabled ? t("settings.on") : t("settings.off")}
        />
      </SettingRow>

      {/* Model selector - specific supplier + role binding */}
      <SettingRow
        title={t("settings.genModel")}
        desc={t("settings.titleGen.genModelDesc")}
      >
        {modelOptions.length > 0 ? (
          <Select.Root
            value={titleGenModel}
            onValueChange={(v) => setTitleGenModel((v as string) ?? null)}
          >
            <Select.Trigger
              disabled={!titleGenEnabled}
              className={cn("w-full", !titleGenEnabled && "cursor-not-allowed opacity-50")}
            >
              <Select.Value>
                {(val: string | null) => (
                  <span
                    className={cn(
                      "flex min-w-0 items-center gap-1.5",
                      !val && "text-content-subtle",
                    )}
                  >
                    <IconRobot size={14} className="text-content-muted" />
                    <span className="truncate">
                      {val
                        ? (modelOptions.find((o) => o.value === val)?.label ?? val)
                        : t("settings.titleGen.modelPlaceholder")}
                    </span>
                  </span>
                )}
              </Select.Value>
            </Select.Trigger>
            <Select.Portal>
              <Select.Positioner>
                <Select.Popup>
                  <Select.List>
                    {modelOptions.map((opt) => (
                      <Select.Item key={opt.value} value={opt.value}>
                        <IconRobot size={14} className="text-content-muted" />
                        <Select.ItemText>{opt.label}</Select.ItemText>
                      </Select.Item>
                    ))}
                  </Select.List>
                </Select.Popup>
              </Select.Positioner>
            </Select.Portal>
          </Select.Root>
        ) : (
          <p className={cn("text-[0.7857em] text-content-subtle", !titleGenEnabled && "opacity-50")}>
            {t("settings.titleGen.noModelsHint")}
          </p>
        )}
      </SettingRow>
    </SettingsSection>
  );
}
